"""Domain layer — pure logic.

No I/O, no async, no globals, and no third-party imports beyond the stdlib and
``pydantic`` (P1). The domain imports nothing else from ``avid``. Home of the
``Event`` envelope (AVID-6), ``RobotState`` + the transition table (AVID-7),
``Affect`` (AVID-8), the ``audio.*`` events + pre-roll ring buffer (#86), the
degraded-mode cue vocabulary ``Cue`` (AVID-80), the ``conversation.*`` events +
``TokenUsage`` value (#99), the ``Fact`` value + ``memory.*`` events + §7.7 scoring
(#116), and ``BBox`` + the ``vision.*`` events (#219), §10.4's interruption policy — the
pure gate that decides whether the robot may speak first (#235) — and ``Axis`` + the gesture
vocabulary, the pure keyframe planner and the ``motion.*`` events (#201).
"""

from avid.domain.affect import (
    SEMANTIC_AFFECTS,
    Affect,
    AffectChanged,
    AffectTier,
)
from avid.domain.audio import (
    ACOUSTIC_RULES,
    ADMISSION_RULES,
    ECHO_FLOOR,
    ECHO_TAIL,
    REACTIVE_BUDGET,
    AdmissionContext,
    AdmissionLimits,
    AdmissionResult,
    Admitted,
    AudioCaptureResumed,
    AudioCaptureStalled,
    AudioPlaybackFinished,
    AudioPlaybackStarted,
    AudioPreRoll,
    AudioSpeechEnded,
    AudioSpeechStarted,
    EchoFloor,
    HighPass,
    Refused,
    evaluate_admission,
    rms_dbfs,
)
from avid.domain.behavior import (
    AMBIENT_SPEECH,
    COOLDOWN,
    DAILY_BUDGET,
    ENGAGED,
    IGNORED,
    POLICY_RULES,
    PRESENCE,
    PROACTIVE_STATES,
    QUIET_HOURS,
    REACTIONS,
    STALE,
    STATE,
    SUPPRESSION_REASONS,
    AmbientWindow,
    BehaviorProactiveDelivered,
    BehaviorProactiveSuppressed,
    BehaviorTriggerDisabled,
    BehaviorTriggerFired,
    Delivered,
    PolicyContext,
    PolicyLimits,
    PolicyResult,
    SpeechEntry,
    Suppressed,
    TriggerRecord,
    ambient_speech_s,
    attribute_speech,
    evaluate_policy,
    record_speech,
    within_quiet_window,
)
from avid.domain.conversation import (
    ConversationAssistantResponded,
    ConversationSessionLost,
    ConversationTurnEnded,
    ConversationTurnStarted,
    ConversationUserTranscribed,
    TokenUsage,
)
from avid.domain.cues import Cue
from avid.domain.events import (
    EVENT_DOMAINS,
    REASON_HANDLER_RAISED,
    REASON_QUEUE_OVERFLOW,
    Event,
    SystemDegradedEntered,
    SystemDegradedExited,
    SystemHandlerFailed,
    SystemShuttingDown,
    SystemStarted,
    validate_event_name,
)
from avid.domain.memory import (
    FACT_KINDS,
    Fact,
    FactKind,
    MemoryFactDeleted,
    MemoryFactStored,
    MemoryFactSuperseded,
    MemoryRecallCompleted,
    RetrievalCandidate,
    RetrievalMatch,
    RoutineSpec,
    ScoredCandidate,
    ScoreWeights,
    deletable_ids,
    rank_candidates,
    recency_decay,
    select_top_facts,
)
from avid.domain.motion import (
    PAN,
    TILT,
    Axis,
    Direction,
    Gesture,
    Keyframe,
    LookAtResult,
    MotionGestureCompleted,
    MotionGesturePreempted,
    MotionGestureStarted,
    duration_ms,
    gesture_for_direction,
    plan,
)
from avid.domain.runtime import BootRecord, StopReason, uptime_ratio
from avid.domain.state import (
    EVENT_TYPES,
    TRANSITION_TABLE,
    IllegalTransition,
    RobotState,
    StateTransitioned,
    Trigger,
    next_state,
)
from avid.domain.vision import (
    BBox,
    VisionFaceDetected,
    VisionPresenceGained,
    VisionPresenceLost,
)

__all__ = [
    # behavior (#235) — §10.4's interruption policy
    "AMBIENT_SPEECH",
    "COOLDOWN",
    "DAILY_BUDGET",
    "POLICY_RULES",
    "ENGAGED",
    "IGNORED",
    "REACTIONS",
    "STALE",
    "SUPPRESSION_REASONS",
    "PRESENCE",
    "PROACTIVE_STATES",
    "QUIET_HOURS",
    "STATE",
    "AmbientWindow",
    "BehaviorProactiveDelivered",
    "BehaviorProactiveSuppressed",
    "BehaviorTriggerDisabled",
    "BehaviorTriggerFired",
    "SpeechEntry",
    "ambient_speech_s",
    "attribute_speech",
    "record_speech",
    "Delivered",
    "PolicyContext",
    "PolicyLimits",
    "PolicyResult",
    "Suppressed",
    "TriggerRecord",
    "evaluate_policy",
    "within_quiet_window",
    # Affect (AVID-8)
    "Affect",
    "AffectChanged",
    "AffectTier",
    "SEMANTIC_AFFECTS",
    "BootRecord",
    "StopReason",
    "uptime_ratio",
    # audio.* events + pre-roll ring buffer (#86) + the echo gate's arithmetic (AVID-159)
    "AudioCaptureResumed",
    "AudioCaptureStalled",
    "AudioPlaybackFinished",
    "AudioPlaybackStarted",
    "AudioPreRoll",
    "AudioSpeechEnded",
    "AudioSpeechStarted",
    "EchoFloor",
    "HighPass",
    "rms_dbfs",
    # the admission gate — who may start a turn (§6.2.4, #467)
    "ACOUSTIC_RULES",
    "ADMISSION_RULES",
    "ECHO_FLOOR",
    "ECHO_TAIL",
    "REACTIVE_BUDGET",
    "AdmissionContext",
    "AdmissionLimits",
    "AdmissionResult",
    "Admitted",
    "Refused",
    "evaluate_admission",
    # conversation.* events + TokenUsage value (#99)
    "ConversationAssistantResponded",
    "ConversationSessionLost",
    "ConversationTurnEnded",
    "ConversationTurnStarted",
    "ConversationUserTranscribed",
    "TokenUsage",
    # Degraded-mode cue bank vocabulary (AVID-80)
    "Cue",
    # Event envelope (AVID-6)
    "EVENT_DOMAINS",
    "REASON_HANDLER_RAISED",
    "REASON_QUEUE_OVERFLOW",
    "Event",
    "SystemDegradedEntered",
    "SystemDegradedExited",
    "SystemHandlerFailed",
    "SystemShuttingDown",
    "SystemStarted",
    "validate_event_name",
    # memory.* events + Fact value + §7.7 scoring (#116)
    "FACT_KINDS",
    "Fact",
    "FactKind",
    "MemoryFactDeleted",
    "MemoryFactStored",
    "MemoryFactSuperseded",
    "MemoryRecallCompleted",
    "RetrievalCandidate",
    "RetrievalMatch",
    "RoutineSpec",
    "ScoredCandidate",
    "ScoreWeights",
    "deletable_ids",
    "rank_candidates",
    "recency_decay",
    "select_top_facts",
    # RobotState (AVID-7); state.transitioned (AVID-69)
    "EVENT_TYPES",
    "TRANSITION_TABLE",
    "IllegalTransition",
    "RobotState",
    "StateTransitioned",
    "Trigger",
    "next_state",
    # BBox + vision.* events (#219). BBox is re-exported by core/hal.py, which is
    # the spelling ports and adapters use — see that module's docstring for why.
    "BBox",
    "VisionFaceDetected",
    "VisionPresenceGained",
    "VisionPresenceLost",
    # motion (#201) — the gesture vocabulary, the pure planner, the motion.* events.
    # ``Axis`` is re-exported by core/hal.py for the same reason ``BBox`` is: a domain
    # event names it, and the layers contract forbids declaring it in core (ADR-009,
    # SDS §3.9.4).
    "PAN",
    "TILT",
    "Axis",
    "Gesture",
    "Keyframe",
    "MotionGestureCompleted",
    "MotionGesturePreempted",
    "MotionGestureStarted",
    "duration_ms",
    "plan",
    # look_at's vocabulary (#204, §6.6) — a direction is not a gesture: Gesture includes NOD
    # and SHAKE, which mean things, while a Direction only points.
    "Direction",
    "LookAtResult",
    "gesture_for_direction",
]
